CREATE DATABASE IF NOT EXISTS `card` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE `card`;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  login VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  avatar VARCHAR(255) NOT NULL DEFAULT 'ava1.jpeg'
);

